"""add devbox vcpus, memory_mb, disk_mb columns

Revision ID: 24af03683ef2
Revises: f8a54c1a865d
Create Date: 2026-03-25 13:01:08.945380

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '24af03683ef2'
down_revision: str | list[str] | None = 'f8a54c1a865d'
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vcpus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('memory_mb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disk_mb', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devbox', schema=None) as batch_op:
        batch_op.drop_column('disk_mb')
        batch_op.drop_column('memory_mb')
        batch_op.drop_column('vcpus')

    # ### end Alembic commands ###
